apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ut9r3jhxf-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:88be2bfe1ea7fabd4dcf35d5cead40976eada633@sha256:9a0f1ec0faf69917e572e2be3cc9a7b8564c20dc71a130bf1e960bf7f99ea3d9
          name: container-image
